version: '3'
volumes:
  data:
services:
  db:
    container_name: "mysql-server"
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
  app:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - '8080:80'
    environment: 
      PMA_ARBITRARY: 1  
      PMA_HOST: db
    depends_on:
      - db      

#docker-compose up -d 
#docker-compose down
#docker system df